export const mamanRendezVousList = [
  "1er trimestre : Prendre rendez-vous avec un médecin généraliste, gynécologue ou sage-femme pour confirmer la grossesse.",
  "Déclarer la grossesse à la Caf et à l'assurance maladie.",
  "Planifier la 1ère échographie.",
  "Bilan prénatal de prévention avec une sage-femme pour les habitudes de vie.",
  "2ème trimestre : Planifier le 2ème examen prénatal.",
  "Planifier l'entretien prénatal précoce avec sage-femme ou médecin.",
  "3ème trimestre : Prévoir le rendez-vous avec l'anesthésiste.",
  "Déclarer la naissance à l'état civil dans les 5 jours suivant l'accouchement.",
  "Planifier les premiers examens de santé du bébé.",
  "Consulter une sage-femme pour un suivi postnatal.",
  "Prévoir la rééducation périnéale et abdominale.",
];

export const babyRendezVousList = [
  "Dans les 8 jours suivant la naissance",
  "Au cours de la 2ème semaine",
  "Avant la fin du 1er mois",
  "1 mois",
  "2 mois",
  "3 mois",
  "4 mois",
  "5 mois",
  "8 mois",
  "11 mois",
  "12 mois",
  "Entre 16 et 18 mois",
  "Entre 23 et 24 mois",
  "2 ans",
  "3 ans",
  "4 ans",
  "5 ans",
  "Entre 8 et 9 ans",
  "Entre 11 et 13 ans",
  "Entre 15 et 16 ans",
];
