import { StyleSheet, Dimensions } from "react-native";

export default StyleSheet.create({
  background: {
    flex: 1,
    width: Dimensions.get("screen").width,
    height: Dimensions.get("screen").height,
    justifyContent: "center",
    alignItems: "center",
  },
  calendar: {
    borderWidth: 1,
    borderColor: "gray",
    height: 320,
    width: 380,
    marginBottom: 100,
    borderRadius: 15,
  },
  title: {
    fontSize: 30,
    textAlign: "center",
    fontFamily: "Caveat",
  },
  // btn: {
  //   backgroundColor: "white",
  //   borderWidth: 1,
  //   width: 120,
  //   height: 30,
  //   alignItems: "center",
  //   borderRadius: 12,
  //   justifyContent: "center",
  //   margin: 5,
  // },
  div_btn: {
    flexDirection: "row-reverse",
    marginBottom: 10,
  },
  header: {
    width: Dimensions.get("screen").width,
    marginBottom: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  modalView: {
    backgroundColor: "white",
    borderRadius: 20,
    padding: 30,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  btnModal: {
    backgroundColor: "pink",
    borderWidth: 1,
    width: 120,
    alignItems: "center",
    borderRadius: 12,
    marginTop: 10,
  },
  // input: {
  //   width: 150,
  //   borderBottomColor: "#ec6e5b",
  //   borderBottomWidth: 1,
  //   fontSize: 16,
  // },
  // textButton: {
  //   color: "#ffffff",
  //   height: 24,
  //   fontWeight: "600",
  //   fontSize: 15,
  // },
  textrole: {
    fontSize: 20,
  },
  modalListView: {
    backgroundColor: "white",
    borderRadius: 20,
    padding: 20,
    width: "65%",
    maxHeight: "70%",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  scrollView: {
    width: "100%",
  },
  listItem: {
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#ccc",
  },
  switchContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  viewGuide: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  alimentationBTN: {
    fontSize: 20,
    height: 50,
    width: 150,
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
    margin: 10,
    borderRadius: 20,
  },
});
